// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCw1rry0OMN4s3EYz0lA96LV2YuvKrbtk',
    appId: '1:985386908620:web:2154a615a8b5ea10e5fb69',
    messagingSenderId: '985386908620',
    projectId: 'weatherly-27d5f',
    authDomain: 'weatherly-27d5f.firebaseapp.com',
    storageBucket: 'weatherly-27d5f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSDKyymsqH5N5reDFAkQk0piiCJSlaJKo',
    appId: '1:985386908620:android:2e58666d14543dfae5fb69',
    messagingSenderId: '985386908620',
    projectId: 'weatherly-27d5f',
    storageBucket: 'weatherly-27d5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDriQXtwxQA6lGY-XGyaNt29yhUEUSND8',
    appId: '1:985386908620:ios:cf7c83d691585dbde5fb69',
    messagingSenderId: '985386908620',
    projectId: 'weatherly-27d5f',
    storageBucket: 'weatherly-27d5f.firebasestorage.app',
    iosBundleId: 'com.example.weatherly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDriQXtwxQA6lGY-XGyaNt29yhUEUSND8',
    appId: '1:985386908620:ios:cf7c83d691585dbde5fb69',
    messagingSenderId: '985386908620',
    projectId: 'weatherly-27d5f',
    storageBucket: 'weatherly-27d5f.firebasestorage.app',
    iosBundleId: 'com.example.weatherly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCw1rry0OMN4s3EYz0lA96LV2YuvKrbtk',
    appId: '1:985386908620:web:090a4ba54d156090e5fb69',
    messagingSenderId: '985386908620',
    projectId: 'weatherly-27d5f',
    authDomain: 'weatherly-27d5f.firebaseapp.com',
    storageBucket: 'weatherly-27d5f.firebasestorage.app',
  );
}
